<Project>
  <PropertyGroup>
    <ModVersion>0.1.2</ModVersion>
    <ModAuthor>Manimal</ModAuthor>
    <ModName>MotionMagic</ModName>
    <ModGuid>com.manimal.motionmagic</ModGuid>
    <ModDisplayName>$(ModAuthor)-$(ModName)</ModDisplayName>
    <ModRepositoryUrl>https://github.com/danauraborealis/Manimal-sMotionMatching</ModRepositoryUrl>
    <Version>$(ModVersion)</Version>
    <AssemblyVersion>$(ModVersion).0</AssemblyVersion>
    <FileVersion>$(ModVersion).0</FileVersion>
    <Authors>$(ModAuthor)</Authors>
    <Product>$(ModDisplayName)</Product>
    <RepositoryUrl>$(ModRepositoryUrl)</RepositoryUrl>
    <SptRoot Condition="'$(SptRoot)' == ''">D:\SPT41Dev</SptRoot>
  </PropertyGroup>
</Project>
